version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ms_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  ms-usuarios:
    container_name: ms-usuarios
    build:
      context: ./
      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./ms-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  ms-cursos:
    container_name: ms-cursos
    build:
      context: ./
      dockerfile: ./ms-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./ms-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - ms-usuarios
    restart: always
#Se definen los volumenes y la red
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring
    external: true