version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ms_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  ms-usuarios:
    container_name: ms-usuarios
    build:
      context: ./
      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: ms_usuarios
      DB_USERNAME: root
      DB_PASSWORD: admin
      CURSOS_URL: ec2-34-229-122-97.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
#Se definen los volumenes y la red
volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
    name: spring